### ISSUE TITLE
Add a Forward button Please

### ISSUE THREAD

**Issue by mthlifan** [mthli/Ninja#1]
Nice browser! I'm a fan.
Can you add a forward button please? so that you can navigate to pages where you have been before and just press forward to go there again after pressing back.

**Comment by mthli** [comment]
Well , actually I **did** add a forward button in Ninja, but I canceled it after for these points:
1. Since Ninja use `WebView`, "back" and "forward" need to load data through network again but not `WebView`'s **cache**, so it looks that "forward" just works like "press the link again", I don't like this behavior so I canceled it.
2. I don't know where should the "forward" button pleced for current design.

Maybe I will add "forward" in future :)

**Comment by mthlifan** [comment]
Ok. can you add fullscreen mode, because it is very useful.

thanks :)

**Comment by mthli** [comment]
Yeah I would like to add fullscreen mode in the future :P

**Comment by mthlifan** [comment]
sometimes downloads crashes the application, when you download the application in background tab too the application crashes, major issue, please fix fast!

**Comment by Thunderbottom** [comment]
Added Forward Button, will post a pull request :)

Regards.

**Comment by mthlifan** [comment]
Thank you :)
